[build]
  command = "npm run functions:install && npm run build"
  publish = "dist/"
  functions = "src/server/functions/"
  [build.processing]
    skip_processing = true

[dev]
  publish = "dist/"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/_pretty/assets/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''

[[redirects]]
  from = "/api/data/*"
  to = "/.netlify/functions/load-data"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render-html"
  status = 200