name: Publish on Netlify
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo ${{ github.base_ref }}

    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - run: npm install

    - run: npm run functions:install && npm run build 

    - name: Production deploy
      if: github.ref == 'refs/heads/master'
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    - name: Preview deploy
      if: github.base_ref == 'refs/heads/master'
      uses: netlify/actions/cli@master
      with:
        args: deploy
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
